version: "3.7"

services:
  jupyter:
    image: battery-dev/jupyter:latest
    build: .
    container_name: jupyter
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_PORT=8888